### ISSUE TITLE
Problemas con lan9252

### ISSUE THREAD

**Issue by jurekalfredo** [ngblume/ethercat-pysoem#2]
estoy tratando de comunicarme con un modulo lan9252 y no puedo, tome de ejemplo tu archivo 
pero no pasa al modo SAFE_OP
podrias ayudarme con esto ?

**Comment by ngblume** [comment]
Hej hej,

I'm very sorry to respond just now.. I never checked the issues neither did I get a notification from GitHub (probably set up incorrectly)...
Freom what Google Translate told me, your are working with the LAN 9252 from Microchip.
I never worked with that module nor with anything other than Beckhoff modules.
Please post your isse over at the SOEM or pySOEM Github pages:
https://github.com/bnjmnp/pysoem
https://github.com/OpenEtherCATsociety/SOEM

Thanks !

Cheers
Niels Göran
