### ISSUE TITLE
Does pySOEM support asynchronous mechanism ?

### ISSUE THREAD

**Issue by jinyistudio534** [ngblume/ethercat-pysoem#3]
Or it can only support threads ?

**Comment by ngblume** [comment]
I have no idea...
I just created this thread example since it served my purpose:
https://github.com/ngblume/ethercat-pysoem/blob/master/separate_thread/separate_thread.py

Please repost the issue in the official repo:
https://github.com/bnjmnp/pysoem

Thanks !

Cheers
Niels Göran
